modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
[[mods]]
    modId="havengrowth"
    version="${file.jarVersion}"
    displayName="Haven Growth"
    logoFile="havengrowth_logo.png"
    credits=""
    authors="CathieNova"
    description="Haven Growth is a mod that allows you to Crouch or Sprint to grow anything that can be Bone Mealed, excluding the blacklisted blocks."
[[dependencies.havengrowth]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.havengrowth]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
