modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
    modId="havengrowth"
    version="${mod_version}"
    displayName="${mod_name}"
    logoFile="havengrowth_logo.png"
    authors="${mod_authors}"
    description='''${mod_description}'''
[[dependencies.havengrowth]]
    modId="neoforge"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.havengrowth]]
    modId="minecraft"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
