blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://discord.gg/7SHEy62xxn
    about: Please ask questions on Haven's Discord.
  - name: Developer Help
    url: https://discord.gg/7SHEy62xxn
    about: Get help with HavenGrowth on Haven's Discord.