name: Crash report
description: >-
  Please use this template when HavenGrowth has caused your game client to crash.  
  If the issue seems to affect only one mod, please report to them first instead of here.
title: '[Crash]: '
body:
  - type: textarea
    id: repro_steps
    attributes:
      label: Steps to Reproduce the Crash
      description: Please explain what we need to do to cause the crash.
      placeholder: >-
        Example:  
        1. When i sprint past something it crashes.
    validations:
      required: true
  - type: input
    id: modpack_url
    attributes:
      label: Mod Pack URL (Optional)
      description: >-
        If you're playing with a mod pack, please include a link to it here.
      placeholder: http://www.Biggest-Modpack-Ever.com
  - type: input
    id: modpack_version
    attributes:
      label: Mod Pack Version (Optional)
      description: >-
        If you're playing with a mod pack, please include its version here.
      placeholder: 0.0.1 Alpha
  - type: textarea
    id: notes
    attributes:
      label: Extra Notes (Optional)
      description: >-
        Optionally, please include anything else you'd like to say about the crash.
      placeholder: >-
        Example:  
        I warned everyone on my server not to do this, so nobody is crashing any more. 
        I just thought I should let you know so you can fix it, thanks!
    validations:
      required: false
  - type: markdown
    attributes:
      value: >-
        ## Sharing your `latest.log`

        In order to diagnose a bug, we will need to see your `latest.log`.  

        To share your `latest.log` here, please follow these steps:


        1. If you don't have it already, find your `latest.log` file.  

        a. [Find your minecraft
        folder](https://stickypiston.co/account/knowledgebase/130/How-do-I-find-my-Minecraft-Folder.html)   

        b. In the minecraft folder, go into the `logs` folder and find the
        `latest.log` file.

        1. Create a Pastebin from the `latest.log`, and copy the url.
  - type: input
    id: crashlog
    attributes:
      label: latest.log
      description: Please paste the url to the gist containing your `latest.log` file.
      placeholder: https://pastebin.com/<your_pastebin_id>
    validations:
      required: true
  - type: markdown
    attributes:
      value: >-
        ## Sharing your Crash Report
        
        In order to diagnose a crash, we will need to see your client crash
        report.  

        To share your client crash report here, please follow these steps:


        1. If you don't have it already, find your client crash report file.  

        a. [Find your minecraft
        folder](https://stickypiston.co/account/knowledgebase/130/How-do-I-find-my-Minecraft-Folder.html)   

        b. In the minecraft folder, go into the `crash-reports` folder and find
        the most recent client crash report file.

        1. Create a Pastebin from the client crash report file, and copy the url.  

  - type: input
    id: crashlog
    attributes:
      label: Crash Report
      description: >-
        Please paste the url to the gist containing your client crash report.
      placeholder: https://pastebin.com/<your_pastebin_id>
    validations:
      required: true
